NewsWeb/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Core.Infrastructure;
using Microsoft.AspNetCore.Mvc.Filters;
using NewsWeb.DataAccess.Repository.IRepository;
using NewsWeb.Models;
using NewsWeb.Utility;
using System.Data;

namespace NewsWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.Category.GetAll()});
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var dataindb = _unitOfWork.Category.Get(id);
            if (dataindb == null)
                return Json(new {success=false,message="Something Went Wrong!!" });
            _unitOfWork.Category.Remove(dataindb);
            _unitOfWork.save();
            return Json(new { success = true, message = "Data Deleted SuccessFully" });
        }
        #endregion
        public IActionResult Upsert(int? id)
        {
            Category category = new Category();
            if (id == null) return View(category);
            category = _unitOfWork.Category.Get(id.GetValueOrDefault());
            if (category == null) return NotFound();
            return View(category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Category category)
        {
            if (category == null) return NotFound();
            if (!ModelState.IsValid) return View(category);
            if (category.Id == 0)
                _unitOfWork.Category.Add(category);
            else
                _unitOfWork.Category.Update(category);
            _unitOfWork.save();
            return View(nameof(Index));
        }
    }
}

NewsWeb/Areas/Admin/Controllers/NewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NewsWeb.DataAccess.Repository.IRepository;
using NewsWeb.Models;
using NewsWeb.Models.ViewModels;
using NewsWeb.Utility;
using System.Data;

namespace NewsWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class NewsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public NewsController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }
        #region
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.News.GetAll(includeProperties:"Category,Place") });
        }
        public IActionResult Delete(int id)
        {
            var newsInDb = _unitOfWork.News.Get(id);
            if (newsInDb == null)
                return Json(new { success = false, message = "Something Went Wrong While Deleting Data!" });
            _unitOfWork.News.Remove(newsInDb);
            _unitOfWork.save();
            return Json(new { success = true, message = "SuccessFully Deleted" });
        }
        #endregion
        public IActionResult Upsert(int? id)
        {
            NewsVM newsVM = new NewsVM()
            {
                News = new News(),
                PlaceList = _unitOfWork.Place.GetAll().Select(pl => new SelectListItem()
                {
                    Text = pl.Name,
                    Value = pl.Id.ToString()
                }
                ),
                CategoryList = _unitOfWork.Category.GetAll().Select(ct => new SelectListItem()
                {
                    Text = ct.Name,
                    Value = ct.Id.ToString()
                })
            };
            if (id == null) return View(newsVM);
            newsVM.News = _unitOfWork.News.Get(id.GetValueOrDefault());
            if (newsVM.News == null) return NotFound();
            return View(newsVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(NewsVM newsVM)
        {
            if (ModelState.IsValid)
            {
                var webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count() > 0)
                {
                    var fileName = Guid.NewGuid().ToString();
                    var extension = Path.GetExtension(files[0].FileName);
                    var uploads = Path.Combine(webRootPath, @"images\news");
                    if (newsVM.News.Id != 0)
                    {
                        var imageExists = _unitOfWork.News.Get(newsVM.News.Id).ImageUrl;
                        newsVM.News.ImageUrl = imageExists;
                    }
                    if (newsVM.News.ImageUrl != null)
                    {
                        var imagePath = Path.Combine(webRootPath, newsVM.News.ImageUrl.Trim('\\'));
                        if (System.IO.File.Exists(imagePath))
                        {
                            System.IO.File.Delete(imagePath);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    newsVM.News.ImageUrl = @"\images\news\" + fileName + extension;
                }
                else
                {
                    if (newsVM.News.Id != 0)
                    {
                        var imageExists = _unitOfWork.News.Get(newsVM.News.Id).ImageUrl;
                        newsVM.News.ImageUrl = imageExists;
                    }
                }
                if (newsVM.News.Id == 0)
                    _unitOfWork.News.Add(newsVM.News);//create
                else
                    _unitOfWork.News.Update(newsVM.News);//edit
                _unitOfWork.save();
                return RedirectToAction("Index");
            }
            else
            {
                newsVM = new NewsVM()
                {
                    News = new News(),
                    PlaceList = _unitOfWork.Place.GetAll().Select(pl => new SelectListItem()
                    {
                        Text = pl.Name,
                        Value = pl.Id.ToString()
                    }
                    ),
                    CategoryList = _unitOfWork.Category.GetAll().Select(ct => new SelectListItem()
                    {
                        Text = ct.Name,
                        Value = ct.Id.ToString()
                    })
                };
                if (newsVM.News.Id == 0)
                {
                    newsVM.News = _unitOfWork.News.Get(newsVM.News.Id);
                }
                return View(newsVM);
            }
        }
    }
}

NewsWeb/Areas/Admin/Controllers/PlaceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NewsWeb.DataAccess.Repository.IRepository;
using NewsWeb.Models;
using NewsWeb.Utility;
using System.Data;

namespace NewsWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class PlaceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public PlaceController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }
        #region APIs
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new {data=_unitOfWork.Place.GetAll()});
        }
        [HttpDelete] 
        public IActionResult Delete(int id)
        {
            var placeInDb = _unitOfWork.Place.Get(id);
            if (placeInDb == null)
                return Json(new { success = false, message = "Something Went Wrong" });
            _unitOfWork.Place.Remove(placeInDb);
            _unitOfWork.save();
            return Json(new { success = true, message = "Data deleted successfully" });
        }
        #endregion
        public IActionResult Upsert(int? id)
        {
            Place place = new Place();
            if (id == null) return View(place);//create
            //edit
            place = _unitOfWork.Place.Get(id.GetValueOrDefault());
            if (place == null) return NotFound();
            return View(place);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Place place)
        {
            if (place == null) return NotFound();
            if (!ModelState.IsValid) return View(place);
            if (place.Id == 0)
                _unitOfWork.Place.Add(place);
            else
                _unitOfWork.Place.Update(place);
            _unitOfWork.save();
            return RedirectToAction("Index");
        }
    }
}

NewsWeb/Views/Shared/_CreateAndBackToListButtons.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-info form-control" style="border-radius: 20px;">
            Save
        </button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control" style="border-radius: 20px;">
            Back
            </a>
    </div>
</div>   

NewsWeb/Views/Shared/_EditAndBackToListButtons.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-info form-control"style="border-radius: 20px;">
            Update
        </button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control" style="border-radius: 20px;">Back</a>
    </div>
</div>

NewsWeb/Views/Shared/_Layout.cshtml
@using NewsWeb.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewsWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NewsWeb.styles.css" asp-append-version="true" />
    @* CSS REF*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    
    </style>
</head>
<body>
    <header style="">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow navbar-dark" style="background-color: #1abc9c;position: fixed; top: 0; width: 100%; z-index: 1000;">
            <div class="container-fluid">
                <img src="~/images/logo/news-logo.png" class="" style="filter: brightness(5) hue-rotate(180deg); width: 120px; height: auto;" />
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><h4 style="font-weight: 700; color: #fff;">Home</h4></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"><h4 style="font-weight: 700; color: #fff;">Privacy</h4></a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><h4 style="font-weight: 700; color: #fff;">Manage</h4></a>
                                <div class="dropdown-menu" style="background-color: #0f0f0f0f;border-radius: 30px;">
                                    <a class="dropdown-item " asp-area="Admin" asp-controller="Place" asp-action="Index">
                                        <h4 style="font-weight: 700;text-decoration: underline;text-decoration-style: double;">
                                            Place
                                        </h4>
                                    </a>
                                    <a class="dropdown-item " asp-area="Admin" asp-controller="News" asp-action="Index"><h4 style="font-weight: 700;text-decoration: underline;text-decoration-style: double;">News</h4></a>
                                    <a class="dropdown-item " asp-area="Admin" asp-controller="Category" asp-action="Index"><h4 style="font-weight: 700;text-decoration: underline;text-decoration-style: double;">Category</h4></a>
                                </div>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>


        <marquee style="color: #da3838; background-color: #fff; font-size: 24px; border-radius: 10px;margin-top:78px;">
            State live news is a news channel specially working for himachal pradesh, covering news about culture, sports, politics and business.It is also the part of Kotkhai09USA ,Founded by Mr.Bharat Bhushan
        </marquee>
    </header>
    <div class="container">
        <main role="main" class="pb-3" style="">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NewsWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @*    JSS REF*@
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery_ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
</body>
</html>
<script>
    console.log("%cWarning: This Website Is Developed By Abhay007! 💀", "font-size: 30px; font-weight: bold; color: red;");
</script>